export interface DataModel {
  SYSTEM_ID: number,
  PARENT_ID: string,
  ORG_ID: number,
  NAME: string,
  STATE: string,
  MODULE_CODE?: string,
  GIT_GROUP_ID?: string,
  CRETED_DATE: number,
  CREATED_BY: number,
  UPDATE_DATE?: string,
  UPDATE_BY?: string,
  SUPPORT_USER_ID?: string,
  ANALYTIC_USER_ID?: string,
  SERVICE_TYPE?: string,
  RESPONSIBLE_DEP_ID?: string,
  HEAD_USER_ID?: string,
  SLA_ANALYTIC_USER_ID?: string,
  OBJ_CODE_ID?: string,
  OBJ_TYPE_ID?: string,
  DESCRIPTION?: string,
}